/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DesignP;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println();
        return true;
    }
}
